//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::answers::Model as Answer;
pub use super::question_tags::Entity as QuestionTag;
pub use super::questions::Model as Question;
pub use super::tags::Model as Tag;
